const sources=[['GmbHG §7','Anmeldung der Gesellschaft','Gesetz über die GmbH'],['GmbHG §8','Inhalt der Anmeldung','Gesetz über die GmbH'],['AO §147','Aufbewahrung von Unterlagen','Abgabenordnung']];
const sourceList=document.querySelector('#sourceList');sourceList.innerHTML=sources.map(s=>`<div class="source"><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join('');
const answers={
 'What documents are required to register a GmbH?':{text:'For a GmbH registration, the application must include the information and documents specified by §8 GmbHG. Among other things, the application states the company name, registered office, domestic business address, business purpose, and the amount of share capital. The managing directors must also make the required declarations. The exact filing package should be checked against the current statutory requirements and the notarial process.',refs:[['GmbHG §8','Inhalt der Anmeldung','Official German legislation']]},
 'How long must accounting documents be retained?':{text:'Under §147 AO, tax-relevant records are subject to statutory retention periods. The applicable period depends on the category of record. The current statutory text should be checked for the specific document before deleting or disposing of it.',refs:[['AO §147','Aufbewahrung von Unterlagen','Official German legislation']]},
 'What does the GmbHG say about registration of a GmbH?':{text:'§7 GmbHG governs the application for registration of the company in the commercial register. The application is made by the managing directors and is connected to the statutory requirements for formation and registration. §8 GmbHG specifies the content of the application.',refs:[['GmbHG §7','Anmeldung der Gesellschaft','Official German legislation'],['GmbHG §8','Inhalt der Anmeldung','Official German legislation']]}
};
function answerFor(q){const exact=answers[q];if(exact)return exact;const lower=q.toLowerCase();if(lower.includes('gmbh')||lower.includes('register'))return answers['What documents are required to register a GmbH?'];if(lower.includes('retain')||lower.includes('aufbewahr')||lower.includes('document'))return answers['How long must accounting documents be retained?'];return {text:'I could not find a sufficiently grounded answer in the current demo knowledge base. TaxHub is designed to abstain rather than invent an answer when the firm's trusted sources do not support the question.',refs:[]}}
function addQuestion(q){document.querySelector('#question').value=q;document.querySelector('#askForm').requestSubmit()}
document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>addQuestion(b.dataset.question)));
const messages=document.querySelector('#messages');
function addAnswer(q){const a=answerFor(q);const refs=a.refs.map(r=>`<div class="source-ref"><span><strong>${r[0]}</strong> · ${r[1]}</span><span>${r[2]}</span></div>`).join('');const el=document.createElement('div');el.className='message assistant';el.innerHTML=`<div class="avatar">T</div><div class="answer-card"><p>${a.text}</p>${refs?`<div class="sources"><strong style="font-size:11px">SOURCES</strong>${refs}</div>`:''}</div>`;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
document.querySelector('#askForm').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#question');const q=input.value.trim();if(!q)return;const user=document.createElement('div');user.className='message';user.innerHTML=`<div class="avatar" style="background:#e8ece8;color:#334039">U</div><div class="bubble">${q.replaceAll('<','&lt;')}</div>`;messages.appendChild(user);input.value='';setTimeout(()=>addAnswer(q),220)});
document.querySelector('#clearBtn').addEventListener('click',()=>location.reload());
document.querySelector('#draftBtn').addEventListener('click',()=>{const out=document.querySelector('#draftOutput');out.classList.remove('hidden');out.innerHTML=`<p class="eyebrow">Generated from grounded knowledge</p><h3>Client request · New GmbH onboarding</h3><pre>Subject: Documents required for your GmbH onboarding\n\nDear Mr / Ms [Name],\n\nTo prepare the registration and onboarding of your GmbH, please provide the documents and information required for the filing. In particular, we will need the company details, registered office and business address, business purpose, share capital information and the formation documents.\n\nPlease send the available documents securely through your usual client portal. We will confirm if anything further is required after review.\n\nBest regards,\n[Steuerkanzlei]</pre><div class="sources"><strong style="font-size:11px">GROUNDED IN</strong><div class="source-ref"><span>GmbHG §8 · Inhalt der Anmeldung</span><span>Official German legislation</span></div></div>`;out.scrollIntoView({behavior:'smooth'})});
