let corpus=[];
const sourceList=document.querySelector('#sourceList');
const messages=document.querySelector('#messages');
async function loadKnowledge(){try{const r=await fetch('./knowledge.json');const data=await r.json();corpus=data.documents||[];sourceList.innerHTML=corpus.map(d=>`<div class="source"><strong>${d.title.split(' — ')[0]}</strong><span>${d.title.split(' — ')[1]||d.source}</span></div>`).join('')}catch(e){sourceList.innerHTML='<div class="source"><strong>Knowledge unavailable</strong><span>Run via a web server.</span></div>'}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function retrieve(q){const terms=q.toLowerCase().split(/\W+/).filter(Boolean);return corpus.map(d=>({...d,score:terms.reduce((n,t)=>n+(d.content+' '+d.title+' '+d.topics.join(' ')).toLowerCase().includes(t)?1:0,0)})).filter(d=>d.score>0).sort((a,b)=>b.score-a.score).slice(0,2)}
function answerFor(q){const docs=retrieve(q);if(!docs.length)return {text:'I could not find a sufficiently grounded answer in the current knowledge base. TaxHub abstains instead of inventing an answer.',docs:[]};let text;if(q.toLowerCase().includes('retain')||q.toLowerCase().includes('aufbewahr'))text='The current §147 AO text sets different retention periods by record category: ten years for the records in §147(1) no. 1 and 4a, eight years for booking documents under no. 4, and six years for other records under §147(1), subject to statutory qualifications.';else if(q.toLowerCase().includes('gmbh')||q.toLowerCase().includes('register'))text='For GmbH registration, §7 GmbHG governs the registration with the commercial register and sets statutory capital-contribution conditions. §8 GmbHG specifies documents and declarations that must accompany the application, including the articles of association, managing-director credentials where applicable and the shareholder list.';else text=docs.map(d=>d.content).join(' ');return {text,docs}}
function addQuestion(q){document.querySelector('#question').value=q;document.querySelector('#askForm').requestSubmit()}
document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>addQuestion(b.dataset.question)));
function addAnswer(q){const a=answerFor(q);const refs=a.docs.map(d=>`<div class="source-ref"><span><strong>${d.title}</strong></span><a href="${d.url}" target="_blank" rel="noreferrer">Open official source ↗</a></div>`).join('');const el=document.createElement('div');el.className='message assistant';el.innerHTML=`<div class="avatar">T</div><div class="answer-card"><p>${escapeHtml(a.text)}</p>${refs?`<div class="sources"><strong style="font-size:11px">SOURCES</strong>${refs}</div>`:''}</div>`;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
document.querySelector('#askForm').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#question');const q=input.value.trim();if(!q)return;const user=document.createElement('div');user.className='message';user.innerHTML=`<div class="avatar" style="background:#e8ece8;color:#334039">U</div><div class="bubble">${escapeHtml(q)}</div>`;messages.appendChild(user);input.value='';setTimeout(()=>addAnswer(q),180)});
document.querySelector('#clearBtn').addEventListener('click',()=>location.reload());
document.querySelector('#draftBtn').addEventListener('click',()=>{const out=document.querySelector('#draftOutput');out.classList.remove('hidden');out.innerHTML=`<p class="eyebrow">Generated from grounded knowledge</p><h3>Client request · New GmbH onboarding</h3><pre>Subject: Documents required for your GmbH onboarding\n\nDear Mr / Ms [Name],\n\nTo prepare the registration and onboarding of your GmbH, please provide the documents and information required for the filing. In particular, please provide the formation documents, managing-director credentials where applicable, shareholder list, and other documents required under the current GmbHG filing requirements.\n\nPlease send the available documents securely through your usual client portal. We will confirm if anything further is required after review.\n\nBest regards,\n[Steuerkanzlei]</pre><div class="sources"><strong style="font-size:11px">GROUNDED IN</strong><div class="source-ref"><span>GmbHG §8 — Inhalt der Anmeldung</span><a href="https://www.gesetze-im-internet.de/gmbhg/__8.html" target="_blank" rel="noreferrer">Official source ↗</a></div></div>`;out.scrollIntoView({behavior:'smooth'})});
loadKnowledge();
